### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/SparkPlan$

### ISSUE THREAD

**Issue by sbvarre** [Intel-bigdata/spark-streamingsql#29]
Hello,

I created a jar for this project and tried to execute the class "UdafEnabledQuery". I keep getting the following error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/SparkPlan$

How do we resolve this?

Thank you.
Sai

**Comment by pratikasarda** [comment]
Hello,

I created a jar for this project and getting same Exception while running 
"WordCountQuery" Example 
on line................. registerDStreamAsTable(dummyStream, "test")

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/SparkPlan$
	at org.apache.spark.sql.streaming.StreamSQLContext.createSchemaDStream(StreamSQLContext.scala:59)
	at com.yash.testcep.WordCountQuery$.main(WordCountQuery.scala:41)
	at com.yash.testcep.WordCountQuery.main(WordCountQuery.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.SparkPlan$
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)






What more needs to be done for this issue?


Thanks
Pratika

**Comment by chenghao-intel** [comment]
Are you using Spark 1.5?

**Comment by pratikasarda** [comment]
No Spark 1.6

**Comment by chenghao-intel** [comment]
This project doesn't support Spark 1.6 yet, since Spark 1.6 changed lots of internal API.

**Comment by pratikasarda** [comment]
Okay Thanks.
Can you suggest supported spark version for this project?

**Comment by chenghao-intel** [comment]
1.4 or 1.5.1 is the supported version, you can check the branch names.

**Comment by pratikasarda** [comment]
After updating spark lib to 1.5.1 I got following Exception for same registerDStreamAsTableline

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/CreateTableAsSelect
	at org.apache.spark.sql.streaming.SchemaDStream.<init>(SchemaDStream.scala:64)
	at org.apache.spark.sql.streaming.SchemaDStream.<init>(SchemaDStream.scala:48)
	at org.apache.spark.sql.streaming.StreamSQLContext.createSchemaDStream(StreamSQLContext.scala:64)
	at com.yash.testcep.WordCountQuery$.main(WordCountQuery.scala:41)
	at com.yash.testcep.WordCountQuery.main(WordCountQuery.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.plans.logical.CreateTableAsSelect
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
